# Generated by Django 6.0.3 on 2026-04-14 14:18

import django.core.validators
import django.db.models.deletion
import re
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/images/"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectToBeDeleted",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_team_id", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RepositoryToBeDeleted",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_repo_id", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("slug", models.SlugField(verbose_name="slug")),
                ("description", tinymce.models.HTMLField()),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="This is for private comments that are only available here.",
                        null=True,
                    ),
                ),
                (
                    "github_team_id",
                    models.IntegerField(
                        blank=True,
                        help_text="This is the id of the team in the GitHub organization. ",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.client",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["semester", "name"],
                "unique_together": {
                    ("name", "semester"),
                    ("slug", "semester"),
                },
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=55,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                "invalid",
                            )
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "github_repo_id",
                    models.IntegerField(
                        blank=True,
                        help_text="This is the id of the GitHub repository.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_archived",
                    models.IntegerField(
                        choices=[
                            (0, "Not archived"),
                            (1, "To be archived"),
                            (2, "Archived"),
                        ],
                        default=0,
                    ),
                ),
                ("private", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Repositories",
            },
        ),
    ]
