# Generated by Django 6.0.3 on 2026-05-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['semester', 'name'], 'permissions': [('can_sync_to_github', 'Can synchronize project(s) to GitHub')]},
        ),
    ]
