# Generated by Django 6.0.3 on 2026-04-23 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["semester", "name"],
                "permissions": [
                    (
                        "can_sync_to_github",
                        "Can batch sync project(s) to GitHub",
                    )
                ],
            },
        ),
    ]
