# Generated by Django 6.0.3 on 2026-05-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("projects", "0002_alter_project_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "semester")},
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
    ]
