# Generated by Django 6.0.3 on 2026-05-22 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_project_default_repo_alter_project_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExistingRepository",
            fields=[],
            options={
                "verbose_name": "Existing Repository",
                "verbose_name_plural": "Existing Repositories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("projects.repository",),
        ),
        migrations.CreateModel(
            name="NewRepository",
            fields=[],
            options={
                "verbose_name": "New Repository",
                "verbose_name_plural": "New Repositories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("projects.repository",),
        ),
    ]
