# Generated by Django 6.0.3 on 2026-05-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['semester', 'name'], 'permissions': [('can_sync_to_github', 'Can batch sync project(s) to GitHub')]},
        ),
    ]
