# Generated by Django 6.0.3 on 2026-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_alter_project_unique_together_alter_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="default_repo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                help_text="The year of the semester is appended to the slug upon saving.",
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
