# Generated by Django 6.0.3 on 2026-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_project_default_repo_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="default_repo",
            field=models.BooleanField(
                default=True,
                help_text="Whether a default repo should be created using the slug name",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                blank=True, unique=True, verbose_name="slug"
            ),
        ),
    ]
