# Generated by Django 6.0.3 on 2026-06-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_existingrepository_newrepository'),
        ('projects', '0010_alter_project_default_repo_alter_project_slug'),
    ]

    operations = [
    ]
