# Generated by Django 6.0.3 on 2026-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="logs",
            field=models.TextField(blank=True, default="", editable=False),
        ),
    ]
