# Generated by Django 6.0.3 on 2026-05-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="fail",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="total",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
