# Generated by Django 6.0.3 on 2026-05-15 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tasks",
            "0004_task_status_alter_task_completed_alter_task_fail_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="data",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
