# Generated by Django 6.0.3 on 2026-05-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_task_date_alter_task_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="date",
        ),
        migrations.AlterField(
            model_name="task",
            name="logs",
            field=models.TextField(
                blank=True,
                default="2026-05-15 13:07:05----------Start of logs----------",
                editable=False,
            ),
        ),
    ]
