# Generated by Django 6.0.3 on 2026-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_remove_task_date_alter_task_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="logs",
            field=models.TextField(
                blank=True,
                default="2026-05-22 12:57:09 START OF LOGS",
                editable=False,
            ),
        ),
    ]
