# Generated by Django 6.0.4 on 2026-06-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='logs',
            field=models.TextField(blank=True, default='2026-06-02 14:34:14 START OF LOGS', editable=False),
        ),
    ]
