# Generated by Django 6.0.3 on 2026-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_task_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="logs",
            field=models.TextField(
                blank=True,
                default="[2026-06-04 16:48:55] INFO: START OF LOGS\n",
                editable=False,
            ),
        ),
    ]
