# Generated by Django 6.0.3 on 2026-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='logs',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
