# Generated by Django 6.0.3 on 2026-04-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("mailing_lists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="users",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="extraemailaddress",
            name="mailing_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing_lists.mailinglist",
            ),
        ),
        migrations.AddField(
            model_name="mailinglistalias",
            name="mailing_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing_lists.mailinglist",
            ),
        ),
        migrations.AddField(
            model_name="mailinglistcoursesemesterlink",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="mailinglistcoursesemesterlink",
            name="mailing_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing_lists.mailinglist",
            ),
        ),
        migrations.AddField(
            model_name="mailinglistcoursesemesterlink",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.semester",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailinglistcoursesemesterlink",
            constraint=models.UniqueConstraint(
                fields=("mailing_list", "course", "semester"),
                name="one_course_semester_per_mailing_list",
            ),
        ),
    ]
