# Generated by Django 6.0.3 on 2026-04-14 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('bigtext', 'Big text'), ('choice', 'Single choice'), ('multi', 'Multiple choice'), ('dropdown', 'Dropdown')], max_length=20)),
                ('label', models.CharField(choices=[('firstname', 'First name'), ('lastname', 'Last name'), ('project1', '1st project preference'), ('project2', '2nd project preference'), ('project3', '3rd project preference'), ('partner1', '1st partner preference'), ('partner2', '2nd partner preference'), ('partner3', '3rd partner preference'), ('devexp', 'Dev Experience'), ('management', 'Management Interest'), ('nondutch', 'Non-dutch'), ('timeslot1', 'Available during scheduled timeslot 1'), ('timeslot2', 'Available during scheduled timeslot 2'), ('timeslot3', 'Available during scheduled timeslot 3'), ('timeslot4', 'Available during scheduled timeslot 4'), ('timeslot5', 'Available during scheduled timeslot 5'), ('timeslot6', 'Available during scheduled timeslot 6'), ('timeslot7', 'Available during scheduled timeslot 7'), ('timeslot8', 'Available during scheduled timeslot 8'), ('timeslot9', 'Available during scheduled timeslot 9'), ('timeslot10', 'Available during scheduled timeslot 10'), ('nonda', 'Has problems with signing an NDA')], max_length=50)),
                ('optional', models.BooleanField(default=False)),
                ('min_choices', models.PositiveIntegerField(blank=True, help_text='Minimum number of choices for MULTI questions', null=True)),
                ('max_choices', models.PositiveIntegerField(blank=True, help_text='Maximum number of choices for MULTI questions', null=True)),
                ('warnings', models.TextField(blank=True, help_text='Warnings to show if validation fails', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('github_id', models.IntegerField(unique=True)),
                ('github_username', models.CharField(max_length=50, unique=True)),
                ('student_number', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('comments', models.TextField(blank=True, help_text='This is for private comments that are only available here.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('follow_up', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='registrations.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='parent_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_questions', to='registrations.questionchoice'),
        ),
        migrations.CreateModel(
            name='MultiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrations.answer')),
                ('choices', models.ManyToManyField(to='registrations.questionchoice')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrations.answer')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.questionchoice')),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.semester')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registrations'),
        ),
        migrations.CreateModel(
            name='RegistrationSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registrations')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registrationsubmission'),
        ),
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrations.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_preference1', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_preference2', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_preference3', models.CharField(blank=True, max_length=50, null=True)),
                ('dev_experience', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')])),
                ('git_experience', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('scrum_experience', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('management_interest', models.BooleanField(default=False)),
                ('is_international', models.BooleanField(default=False)),
                ('available_during_scheduled_timeslot_1', models.BooleanField(default=True)),
                ('available_during_scheduled_timeslot_2', models.BooleanField(default=True)),
                ('available_during_scheduled_timeslot_3', models.BooleanField(default=True)),
                ('available_during_scheduled_timeslot_4', models.BooleanField(default=True)),
                ('available_during_scheduled_timeslot_5', models.BooleanField(default=True)),
                ('available_during_scheduled_timeslot_6', models.BooleanField(default=True)),
                ('available_during_scheduled_timeslot_7', models.BooleanField(default=True)),
                ('available_during_scheduled_timeslot_8', models.BooleanField(default=True)),
                ('available_during_scheduled_timeslot_9', models.BooleanField(default=True)),
                ('available_during_scheduled_timeslot_10', models.BooleanField(default=True)),
                ('has_problems_with_signing_an_nda', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('preference1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
                ('preference2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
                ('preference3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
                ('projects', models.ManyToManyField(blank=True, to='projects.project')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['semester'],
                'unique_together': {('user', 'semester')},
            },
        ),
    ]
