# Generated by Django 6.0.3 on 2026-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrations",
            name="projects",
            field=models.ManyToManyField(blank=True, to="projects.project"),
        ),
    ]
