# Generated by Django 6.0.3 on 2026-04-30 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('registrations', '0003_registrationsubmission_projects_alter_question_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsubmission',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(choices=[('firstname', 'First name'), ('lastname', 'Last name'), ('project1', '1st project preference'), ('project2', '2nd project preference'), ('project3', '3rd project preference'), ('course', 'Course'), ('partner1', '1st partner preference'), ('partner2', '2nd partner preference'), ('partner3', '3rd partner preference'), ('devexp', 'Dev Experience'), ('management', 'Management Interest'), ('nondutch', 'Non-dutch'), ('timeslot1', 'Available during scheduled timeslot 1'), ('timeslot2', 'Available during scheduled timeslot 2'), ('timeslot3', 'Available during scheduled timeslot 3'), ('timeslot4', 'Available during scheduled timeslot 4'), ('timeslot5', 'Available during scheduled timeslot 5'), ('timeslot6', 'Available during scheduled timeslot 6'), ('timeslot7', 'Available during scheduled timeslot 7'), ('timeslot8', 'Available during scheduled timeslot 8'), ('timeslot9', 'Available during scheduled timeslot 9'), ('timeslot10', 'Available during scheduled timeslot 10'), ('nonda', 'Has problems with signing an NDA'), ('comments', 'Comments')], max_length=50),
        ),
    ]
