# Generated by Django 6.0.3 on 2026-05-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_registrationsubmission_course_alter_question_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(blank=True, choices=[('first_name', 'First name'), ('last_name', 'Last name'), ('email', 'Email'), ('github_username', 'GitHub username'), ('github_id', 'GitHub ID'), ('student_number', 'Student number'), ('course', 'Course'), ('project1', '1st project preference'), ('project2', '2nd project preference'), ('project3', '3rd project preference'), ('course', 'Course'), ('partner1', '1st partner preference'), ('partner2', '2nd partner preference'), ('partner3', '3rd partner preference'), ('devexp', 'Dev Experience'), ('management', 'Management Interest'), ('nondutch', 'Non-dutch'), ('timeslots', 'Timeslot availability'), ('nonda', 'Has problems with signing an NDA'), ('comments', 'Comments')], max_length=50, null=True),
        ),
    ]
