# Generated by Django 6.0.2 on 2026-04-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_question_max_choices_question_min_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_questions', to='registrations.questionchoice'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('bigtext', 'Big text'), ('choice', 'Single choice'), ('multi', 'Multiple choice'), ('dropdown', 'Dropdown')], max_length=20),
        ),
    ]
