# Generated by Django 6.0.3 on 2026-04-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_question_parent_choice_questionchoice_follow_up_and_more'),
    ]

    operations = [
    ]
