# Generated by Django 6.0.3 on 2026-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0020_merge_20260403_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("bigtext", "Big text"),
                    ("choice", "Single choice"),
                    ("multi", "Multiple choice"),
                    ("dropdown", "Dropdown"),
                ],
                max_length=20,
            ),
        ),
    ]
