# Generated by Django 6.0.3 on 2026-05-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registrations",
            "0004_registrationsubmission_course_alter_question_label",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("bigtext", "Big text"),
                    ("choice", "Single choice"),
                    ("multi", "Multiple choice"),
                    ("dropdown", "Dropdown"),
                ],
                max_length=20,
            ),
        ),
    ]
