# Generated by Django 6.0.3 on 2026-05-22 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0005_alter_question_label"),
        ("registrations", "0021_alter_question_question_type"),
    ]

    operations = []
