# Generated by Django 6.0.4 on 2026-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_merge_20260522_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(blank=True, choices=[('first_name', 'First name'), ('last_name', 'Last name'), ('email', 'Email'), ('github_username', 'GitHub username'), ('github_id', 'GitHub ID'), ('student_number', 'Student number'), ('course', 'Course'), ('projects', 'Project preferences'), ('partners', 'Partner preferences'), ('devexp', 'Dev Experience'), ('management', 'Management Interest'), ('nondutch', 'Non-dutch'), ('timeslots', 'Timeslot availability'), ('nonda', 'Has problems with signing an NDA'), ('comments', 'Comments')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('bigtext', 'Big text'), ('textlist', 'Text list'), ('choicelist', 'Choice list'), ('choice', 'Single choice'), ('multi', 'Multiple choice'), ('dropdown', 'Dropdown')], max_length=20),
        ),
    ]
