# Generated by Django 6.0.4 on 2026-05-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_alter_question_label_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(blank=True, choices=[('first_name', 'First name'), ('last_name', 'Last name'), ('email', 'Email'), ('github_username', 'GitHub username'), ('github_id', 'GitHub ID'), ('student_number', 'Student number'), ('course', 'Course'), ('projects', 'Project preferences'), ('partners', 'Partner preferences'), ('devexp', 'Dev Experience'), ('gitexp', 'Git Experience'), ('scrumexp', 'Scrum Experience'), ('management', 'Management Interest'), ('nondutch', 'Non-dutch'), ('timeslots', 'Timeslot availability'), ('nonda', 'Has problems with signing an NDA'), ('comments', 'Comments')], max_length=50, null=True),
        ),
    ]
