# Generated by Django 6.0.3 on 2026-06-02 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0024_alter_question_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrations",
            options={
                "verbose_name": "Registration",
                "verbose_name_plural": "Registrations",
            },
        ),
    ]
