name: "Linting"
on: "push"

jobs:
  lint:
    name: "Linting"
    runs-on: "ubuntu-latest"
    steps:

    - name: "Checkout the repository"
      uses: "actions/checkout@v4"

    - name: "Setup Python"
      uses: "actions/setup-python@v3"
      with:
        python-version: '3.14'

    - name: "Install uv"
      uses: astral-sh/setup-uv@v7

    - name: ruff-action
      uses: astral-sh/ruff-action@v3.6.1

    - name: "Run Black"
      run: "uv run black --quiet --check website"

    - name: "Run flake8"
      run: >-
        uv run
        flake8
        --max-line-length=119 --extend-ignore=E203,W503
        --exclude="migrations,website/giphousewebsite/settings/,website/registrations/models/__init__.py"
        --application-import-names="$(ls -1 website/*/__init__.py | awk -F'/' 'BEGIN { ORS = "," } {print $(NF-1) }')"
        website
